version: "3.9"
services:
  server:
    image: vividynamics/default-backend-server
    build: .
    restart: "always"
    ports:
      - ${PORT}:${PORT}
    environment:
      RACK_ENV: $RACK_ENV
      BIND_ADDRESS: $BIND_ADDRESS
      PORT: $PORT
